---
- name: install base php packages
  yum: pkg={{ item }} state=present
  with_items:
     - "{{ php_base_name }}"
     - "{{ php_base_name }}-common"
     - "{{ php_base_name }}-cli"
     - "{{ php_base_name }}-pear"
     - "{{ php_base_name }}-pdo"
  tags:
    - packages
    - php

- name: install our common php packages
  yum: pkg={{ item }} state=present
  with_items:
     - "{{ php_base_name }}-gd"
     - "{{ php_base_name }}-mbstring"
     - "{{ php_base_name }}-mcrypt"
     - "{{ php_base_name }}-process"
     - "{{ php_base_name }}-soap"
     - "{{ php_base_name }}-xml"
  tags:
    - packages
    - php

- name: install php fpm
  yum: pkg="{{ php_base_name }}-fpm" state=present
  when: php_fpm == true
  tags:
    - packages
    - php

- name: install mod_fastcgi for fpm
  yum: pkg="mod_fastcgi" state=present
  when: ansible_distribution_major_version|int < 7 and php_fpm == true
  tags:
    - packages
    - php

- name: install php jsonc
  yum: pkg="{{ php_base_name }}-pecl-jsonc" state=present
  when: php_version > 5.4
  tags:
    - packages
    - php

- name: install php mysqlnd
  yum: pkg="{{ php_base_name }}-mysqlnd" state=present
  when: php_version > 5.4
  tags:
    - packages
    - php

- name: install php mysql
  yum: pkg="{{ php_base_name }}-mysql" state=present
  when: php_version < 5.5
  tags:
    - packages
    - php

- name: install php opcache for IUS on CentOS 6
  yum: pkg={{ item }} state=present
  with_items:
     - "{{ php_base_name }}-opcache"
     - "{{ php_base_name }}-pecl-apcu"
  when: ansible_distribution_major_version|int == 6 and php_version > 5.3
  tags:
    - packages
    - php

- name: install php opcache for IUS on CentOS 7
  yum: pkg={{ item }} state=present
  with_items:
     - "{{ php_base_name }}-opcache"
     - "{{ php_base_name }}-pecl-apcu"
  when: ansible_distribution_major_version|int == 7 and php_version > 5.4
  tags:
    - packages
    - php

- name: install php opcache on Centos 7
  yum: pkg={{ item }} state=present
  with_items:
     - "{{ php_base_name }}-pecl-zendopcache"
     - "{{ php_base_name }}-pecl-apcu"
  when: ansible_distribution_major_version|int == 7 and php_version == 5.4
  tags:
    - packages
    - php

- name: install php memcache driver
  yum: pkg="{{ php_base_name }}-pecl-memcache"
  when: php_use_memcache == true and php_version < 5.6
  tags:
    - packages
    - php

- name: install php memcached driver
  yum: pkg="{{ php_base_name }}-pecl-memcached"
  when: php_use_memcached == true
  tags:
    - packages
    - php

- name: configure php.ini
  template: src=php.{{ php_version }}.ini.j2 dest=/etc/php.ini mode=0644 owner=root group=root
  notify: 
    - restart php
  tags:
    - configuration
    - php

- name: configure php httpd module
  template: src=10-php.conf.j2 dest=/etc/httpd/conf.modules.d/10-php.conf owner=root group=root mode=0644
  notify:
    - restart httpd
  tags:
    - configuration
    - php
    - httpd

- name: configure httpd for php
  template: src=php.conf.j2 dest=/etc/httpd/conf.d/php.conf owner=root group=root mode=0644
  notify:
    - restart httpd
  tags:
    - configuration
    - php
    - httpd
