---
- name: set session and cache base dirs
  set_fact:
    php_write_dir: /var/lib/php/fpm
  when: php_source == "IUS" and php_version > 5.6

- name: set session and cache base dirs
  set_fact:
    php_write_dir: /var/lib/php-fpm
  when: php_source != "IUS" or php_version <= 5.6

- name: setup php packages
  include: packages.yml
  tags:
    - packages
    - php

- name: configure php.ini
  template:
    src: php.{{ php_version }}.ini.j2
    dest: /etc/php.ini
    mode: 0644
    owner: root
    group: root
  notify: 
    - restart php
  tags:
    - configuration
    - php

- name: setup php fpm
  include: fpm.yml
  tags:
    - packages
    - configuration
    - php
    - services

- name: configure php httpd module
  template:
    src: 10-php.conf.j2
    dest: /etc/httpd/conf.modules.d/10-php.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int > 6
  notify:
    - restart httpd
  tags:
    - configuration
    - php
    - httpd

- name: configure php httpd module in conf.d
  template:
    src: 10-php.conf.j2
    dest: /etc/httpd/conf.d/10-php.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_major_version|int < 7
  notify:
    - restart httpd
  tags:
    - configuration
    - php
    - httpd

- name: configure httpd for php
  template:
    src: php.conf.j2
    dest: /etc/httpd/conf.d/php.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd
  tags:
    - configuration
    - php
    - httpd

- name: install composer
  include: composer.yml
  when: development is defined and development or php_development or php_composer
  tags:
    - php
    - composer
    - development
    - packages

- name: install codeception
  include: codeception.yml
  when: development is defined and development or php_development or php_codeception
  tags:
    - php
    - codeception
    - development
    - packages

- name: install other development packages
  include: development.yml
  when: development is defined and development or php_development
  tags:
    - php
    - development
    - packages
