- name: install php packages
  yum:
    name: "{{ php_base_packages + php_common_packages + php_additional_packages }}"
    state: present
  tags:
    - packages
    - php

- name: install pear
  yum:
    name: "php-pear"
    state: present
  tags:
    - packages
    - php

- name: install php mysqlnd
  yum:
    name: "{{ php_base_name }}-mysqlnd"
    state: present
  when: php_version > 5.4
  tags:
    - packages
    - php
