---
- name: restart php
  command: /bin/true
  notify:
    - restart php-fpm
    - restart php-httpd

- name: restart php-fpm
  service: name=php-fpm state=restarted
  when: php_fpm == true

- name: restart php-httpd
  service: name=httpd state=restarted
  when: php_fpm == false
